language: node_js
sudo: required
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
env:
  global:
    - secure: >-
        gHy8OTch7/ynhy1iZL4s11/vuHHQinATOWWXpYE5F+IvXF4W4Iiw/YLGNtPfMR0aE8mv8OJfdfcut8I3z6Wlg6yEoGyMvNZBoe/qb1RDvRRCx3/V4vO3l80QOkGdNbGvFApnGY4SGsNmjp0Pix+R1CKwnQ/QfZBHJBgtoVlje4FejDul/9YGU6UNDZ8V+j5nqeO5CuwBTwSXNRiJRmYbDBnE52YgXyJo9y2spsJXTPb0yfO43axMrV3jm3/cbNdgx+u4jgCsar50No9es1l1t/EebMwnaHlMN5z6TcIcj6bfmrfKcu1OtlAig3ZNQK/bKC1f8kzaK0waoHovEAhK5118oZxM7wsk1Anw5dzjjfPIUbtRLNR/A/Cn/TFCdjQy2YWNBkBpIx6c+D25QyHzHpAU98dkizElFgTl3jAI4QQQBDeYKShk4jIoJ+oFjMnr3LiW7aslmg53gK30nyXv9ExH9FxUdKwD1IV7bxPDn/2rxi6Q/IqGD95oHWdyS94IF6jd+MKa+nujcnORxmisUHYbNPbBLeuwF4YJUMXCafkgUCQL5NVvZVxRoW2+0FIjQ4QbhwX8zIYR9PGhnSHBMMzgjX4qb8MGYq038Pb6rqfiwyE3rucpnq0lylr/hNlWpKEPbg4MATzwLZ8vQsXIY7XWMdMOniSIi3+r/Y0xyRk=
    - secure: >-
        wxErWc0KMbQ1NBiOF2izDEHrx3UI603LO+dqDFnUvN0al/E10A0CJXyvtkBWMPoY4oMIfckrzF4/XnjlnNmliKCyEq9uKyhEVhk2y8hH1a8rcbgZUTls+kq1RmWJX8GchH/0J03YsVoDD6nJAPRkFMli6hBcfW5p4mo1ls9pZdm5NbB/CV/MHvilvsntdVsDCz/n7DKa/SZLQ8U4vSU/0o92XQrUNyUr5ehtefw4aVMdXLT07NGHOjRFG+3GJADzRESaurq5rcSR/tjrToJnLmVdDrVP08HfjIT/y+2O2dHzrZ302eVOoy/DCf5gJ0oygDja83bP9s+044qGgOLa6OxUn0kp6gblYpgMf9V8dpGiT4rGV1x3HgC5s9gDo8YXvewnJwCbuU8ROrgfGHKFsX6uYh+ZDffTiu+GX7s2sk9P+d89WCpt7J9kLvV3slwtIJbS9+ck721HFZYOaTUX3yAyEeBqml8J3MoVUBXM9cQr9w6bgbW2cXppkAa1jTXQZ5ZolF7Wg+OFjtzAQAWay1r+dhOIAcoiQLUle55b+HrdwDHnzeoMWhWzLGWIciGoJZ78Bm0TIIvKhnecBXwV4KsKnP1Q/mV4GkWCTkAlQ49tEfcFn7HN/xMCQmYJ3WIw+piA9KUVMAGnZ3EXEXRl9CHCnplc/FYstb4L7MmPUoA=
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s ''default''; fi'
dist: trusty
