language: node_js
sudo: false
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
env:
  global:
    - secure: IeduJKZ5H+TsCRwfwNOoEstetORsPkDHTqKRQBf5t7VbWDS7YArhWXSKh3ebowi8trqFF5Zie0k6hvaGgVgrcM07JRZVtDkyi0SNcyQcBAZd5q9sNfrp2fFZPec7gNfL1yAXDGEToQQPfkYnn80t5ZHJfc015al2FbWnYgvO5ZjnQe16Xz0MVGJJ62ItF+2Yv3jTPmI9xVm6gGLL9ZbVr8SPGB2V/mvwmyG2PczwUNYXcZZHvZxmbRlzjfj7BuhUAnKRzp+WuPftItKPp+I0xhNABd/fQQ2GtvkAyQMaD1rG7KcPNwTYJ7UrTKTjiXnS7XbXS9sPjWbI8O+10V7L7vjwyHA4dJBWrQgYMqlhQn5iDYZJPYrmfSuGkyjogIx/C2GP6W1Ni0BB1qienc4i2JNPZlLOMV2U25QY8MgpdaasyKJasXSK1HPMovRwTBfgRXvHMgBz1G+H4kr7DTVkvEtbLFO65XkzOX53DFjxSbNJA59kXheCWrFz4jlS52DPN/DQHk9cjcp9XwKK0UpIzzsLaj5qO03BNOlrrOC8gxXPWuok/kxFtPnDEPgfz87NHCf2Oq908hgROdrJK7Xt7A0jfR3fEbidTC6HugtsfhsDd4xQpWjHLusrcci6IrKSusxA4asN2J+vBPGqVOehw4N9VDquuvNePAcj/ovwNos=
    - secure: bXuJJh349mBmjl4yxqS5YN+nNeAxq/RenAr4RVy4davrqCB5U67UAr1l5uCJuhQskrTLX2CgucTME3EMr2snvVEKqB3xjPWrwXHa8rShycVPnrNOXLZwwWzVDq3GWCv5W2g+Smh1wcbERYjo16DYAV2jAaDvsRvBgUe5PCYvG0+1V7gAOXo0tiRpIneqMAMAqoM1r+mhqeoUsTRzsMTHKF2zOctLeLtbXwB2HhGzAB2HJswE44pLdPjO7iGIJmTk2knzyRfkLh0Jl9+lSGBvUsL/LXnDCFPiHpU3FX5wGDRZEA0oV8KII/xsClflssKkugbfnH8edTbzp9P92cbameQc3Dz9HRVY+bKI56rS75xF4Tp/TCFvAqBEgS6y4ZqOqtYXP7qrV/eOANlb94q+0duCcCC9UG63nYR+vUIHkebV8czWYTbp1Qtmed7lTeSSlub/1dyeGPJPG130wE7FxVAK5QiK+E3Fbi21xJ55cglFUtuje6P1j8ByRpA3QUflENCTrusAhIkCN2jjcfZGrFEgcxDv8F0dI2SHieC3XMbPpaTTJtDImoDghjrzjNNnTbfgop/a5TTNOsyQKqKj2ervbYAWvM3Rs+VtTlRjOxNnRKJIJrniOTItanWKOLzSzdUPh2dbAPIILAEE3jnD5DP8dVp2g5Oi6djTAPRHRJ8=
node_js: 4
addons:
  firefox: '42.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
