language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: fviqObsjTcudSB+jLADACiHgRXQLw3s0myKUpVSbRnNlvcwzfXulFTpwV3vRftieBfj1vupwhJOTjFWtD9MYTRS6tcSSE6ShUNLOcyiZmb4kR9Ox3rQAvUfME9Yj2dh2txFYgMhhLEuGQkdM3BvxPTPmWEoKjGCSnqvga26Kddm4++GPE7+s14t5Iq0q+KWiqJ0rscaQrEwYKrBTPiv93abkPkajKN9nMZD1EfUYo03wDBMHGzF7RCV5cfZQUqhpK64DvTRpvtErZOvJX2dSz3GbhuYH1lDHMIHIEFMhGk/Ayu9lzEfnExbWYQydxW3yfmeGRmSnpmKcz3eTdlMCB9sX9k8IY8RCCjG4jS9iPpcDh/0aGHw+S7v0iyx9X7eq1hOz6n8ZouUVYGZEf7gt4EtWEsYVxSANQkvBhDhfJMCWdz/uv+AOV6SMjh9pwakifdDNGF/PifcFsfgbYaJyyEPH0faQs+0PQG+jciuUAd3W/5DO6Iilbc7rJJENaDNNucjx+eYwSNuW7vKj3XkyEMT8R1t7t041gXTgjElowI35kUkBTI7HZTI4RwTb/+rDqyncBk6x9BdYkq2EGM1zaqQzTD7PlrJ686IRRL2WmA1dOQYzlOv4muyPmnNKnRLYyMjF6niANrXXoZn7rTI6AcsieUUoyyonZ62Fg9mjcrs=
  - secure: jH5Cn/56zXgH14Y0+0X6YhqVqabe47VLWD5zPePIpRDust4SBDJ6mqalAIWfT3+RLZR5x5+dQIBO3V3BQ5KFOB5E+EEserzqNbqIEHx+crkhztg+lBmedMgGU8+gTa8D3Htd1kYNN+KMnsxShCQbWd+psIb6Uje9BhdMBVgoBAkitvTYDMI69qU14UgNYpE6qvf28K9WZBPxSWeRVa5OtS4I4QixYLRy9zcmIWWsesAqd+84Hj5hybIL9iZgo4UzddYd0GBwiaAXwIKnb7DpQDOsomuQaoKWI3HWZSlXEP+9cvWQ6UafaaeKifob5PtnPeVq2E4m8CVseuFN5h5mSnA3RX0EQUz+e6BJJeWPQ684MDrda3A3yfbG47jYrzQ8iQWY7nfUOKPR2sDdDAPBQh7kjnS8VtAvALCnlDi79y08UPSrsQXOYkJNYBSabmguGVOKNPrfFz3ct0Q9KWhCK5MEA7hArIvYW9K3YpGOYBdJmx8vr+BNGVb/45mBYh57Fgw0ij+Di37AvAR3BWJJIifBqfML8MBEUjqfr1Gkjli1rLuvgis4OFmmcIqM5ZvO8gG3gzOf1Ma/YjFraCESnoyjH30W4pF7uzeLcRjNb3clWyCQeYqptD4UgQfBH4oIyddhqwfDJOfV32zrm/woGFo0Z5vb0kD0F8uBKiodh/I=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
