language: node_js
sudo: required
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
env:
  global:
    - secure: UMolJPFoQyMtTKW90zNgY1PjOu9dfnUaFDt8C/fd8vgJKvVV0XT+Zga4OVwf87FM7Svwf6zuMaDgkc50vP9CicAMb9ifxWD1ymA+HhufIms8KpiGGJuKfZRdeHoxlCV3oxSwyqhTKLHptvVLs59d9q3NbiwoxY7maJ7wUfc1HU/HVi/AvLFFFhPO3sjSWwgsIX6iIh8+7I9Zb2Ni13m7mp1gfgX5rqjUB0tywFnxkyepSn1RWkUlJRhLxMAYHx3ND36G+lGMZIOXlHrm/pZ+CmrvO4MuvVEXe0zXh24PpGBicILVzvvey5kk3VzUOnhEKq/nrTrOOmYL/hSUtQeXoHsG2dhV/6BA8GXhuAtE4v2NK6PA44K5v0rGlwsLiz1xlfScR0VZ2b5h8NLEhUcTNsAxP02bHPAlo3POWckdxUYfLMfu8bRsBrN+/8ORe5PPomgXkkooylLSDN9iZeuzdEQb5l3uJ8jogYJZXJynsBCWaj1CI7WkDRTFfMo238p/UeA8q3RMWOKYU9mCzZXblFazVVtAa8haPpGlMrAkmhtHqgigIlzKdgWzTZq6FXicODFqLYo2/Pn4dvd/1yl70W10uI+1Sg9B/wtpyL5MiQ5OVMsaTYOUvS9FYQ/0Zfz2Sc5eGQi9Sfa6tYVPVrNtodjUMUQtWvv9vrT3dWb1aW0=
    - secure: UJWcpPmOokTciVINToo0ikkyAtrilHK5FRUL0/ZssJeljUiFeBWvXtjg2s8aGY3Yk7wW9DJ8CNUEp6jNelts1H/JNsrcOzd+BaP+j/GqCBby/KQr3kJDVTBnJlsReE0EKgwH0iDos8xiEqesnmW0q+CSsTI1mDnZKVk0GCMcBIh/eu68Rg+83pP9Lbm0cYsmvLj0WpJFzuSRlEWV+aCnyxdv3Q51QyqNzKBACVz757nuEMN3UCvpArxUZME6XKKuCCDDDPbdI4E+Vmbzoz8uTY6k4nOV9mBy5J1b4yLQfGQVaLqlZSs/0iTLneDsIB9sFtZQKiRKfi1MB9Hu1Q3Itje5JkU6spb0mrdpewqgA2Az4e9oPewl0kg6F8gtvnnsJfAJQz5UFHJdGEQSNgIqhJ8a9CF+5t2VNhCis1oUDUUYbiB+fLm83pm2yKQMYpyHvYFZTJBfPLwzfM8UJ5mzEoNDZi4Mdc0koPrF8AzP2oacw3EHJ8AeMSop69NL1ZFWWaBiqIByEEOQrUFi2J2iAmHC/46Kqp88z/IajAfepRrvE7ViwEHF9pc0C0ySs9N2SgmzVhm0NN9KGgvKLW8SNafSHylUdxWKxP7YugITjS/vXdKp3emshk42WLcnijx8oVVMVFUp1q3A2pOepvPqmV//fsaQoxleea3OLaIh+yY=
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
dist: trusty
